import type { Product } from './types';

export const brands = ['Ray-Ban', 'Oakley', 'Gucci', 'Prada', 'Technoii'];
export const styles = ['Aviator', 'Wayfarer', 'Cat Eye', 'Round', 'Rectangular', 'Sport'];
export const materials = ['Acetate', 'Metal', 'Titanium', 'Plastic'];
export const lensTypes = ['Polarized', 'Non-Polarized', 'Gradient', 'Mirrored', 'Blue Light'];

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Aviators',
    description: 'Timeless aviator sunglasses with a metal frame. Perfect for any occasion, offering both style and UV protection.',
    price: 150,
    imagePlaceholderId: 'product-1',
    category: 'Sunglasses',
    brand: 'Ray-Ban',
    style: 'Aviator',
    material: 'Metal',
    lensType: 'Non-Polarized',
  },
  {
    id: '2',
    name: 'Modern Wayfarers',
    description: 'A modern take on the classic wayfarer design, featuring a lightweight acetate frame and polarized lenses.',
    price: 180,
    imagePlaceholderId: 'product-2',
    category: 'Sunglasses',
    brand: 'Oakley',
    style: 'Wayfarer',
    material: 'Acetate',
    lensType: 'Polarized',
  },
  {
    id: '3',
    name: 'Elegant Cat Eye Frames',
    description: 'Chic and sophisticated cat eye prescription glasses. Made from premium acetate for a comfortable fit.',
    price: 220,
    imagePlaceholderId: 'product-3',
    category: 'Eyewear',
    brand: 'Prada',
    style: 'Cat Eye',
    material: 'Acetate',
    lensType: 'Non-Polarized',
  },
  {
    id: '4',
    name: 'Vintage Round Glasses',
    description: 'Inspired by vintage designs, these round glasses feature a thin metal frame and adjustable nose pads.',
    price: 130,
    imagePlaceholderId: 'product-4',
    category: 'Eyewear',
    brand: 'Technoii',
    style: 'Round',
    material: 'Metal',
    lensType: 'Non-Polarized',
  },
  {
    id: '5',
    name: 'Titanium Rectangular Frames',
    description: 'Ultra-lightweight and durable rectangular frames made from pure titanium. Perfect for everyday wear.',
    price: 300,
    imagePlaceholderId: 'product-5',
    category: 'Eyewear',
    brand: 'Technoii',
    style: 'Rectangular',
    material: 'Titanium',
    lensType: 'Blue Light',
  },
  {
    id: '6',
    name: 'Performance Sport Sunglasses',
    description: 'Aerodynamic and durable sport sunglasses designed for high-performance activities, with mirrored lenses.',
    price: 250,
    imagePlaceholderId: 'product-6',
    category: 'Sunglasses',
    brand: 'Oakley',
    style: 'Sport',
    material: 'Plastic',
    lensType: 'Mirrored',
  },
  {
    id: '7',
    name: 'Daily Comfort Contact Lenses',
    description: 'A 30-day pack of daily disposable contact lenses that provide exceptional comfort from morning to night.',
    price: 45,
    imagePlaceholderId: 'product-7',
    category: 'Contact Lenses',
    brand: 'Technoii',
    style: 'N/A',
    material: 'N/A',
    lensType: 'N/A',
  },
  {
    id: '8',
    name: 'HD Vision Polarized Lenses',
    description: 'Upgrade your frames with our high-definition polarized lenses, reducing glare and enhancing clarity.',
    price: 90,
    imagePlaceholderId: 'product-8',
    category: 'Lenses',
    brand: 'Technoii',
    style: 'N/A',
    material: 'N/A',
    lensType: 'Polarized',
  },
  {
    id: '9',
    name: 'Sleek Metal Frames',
    description: 'Minimalist metal frames with a sleek, modern design. Available in multiple colors.',
    price: 165,
    imagePlaceholderId: 'product-9',
    category: 'Eyewear',
    brand: 'Gucci',
    style: 'Rectangular',
    material: 'Metal',
    lensType: 'Non-Polarized',
  },
  {
    id: '10',
    name: 'Designer Gradient Sunglasses',
    description: 'Oversized designer sunglasses featuring beautiful gradient lenses and a bold acetate frame.',
    price: 350,
    imagePlaceholderId: 'product-10',
    category: 'Sunglasses',
    brand: 'Gucci',
    style: 'Cat Eye',
    material: 'Acetate',
    lensType: 'Gradient',
  },
  {
    id: '11',
    name: 'Monthly Wear Contact Lenses',
    description: 'A 6-month supply of comfortable and breathable monthly contact lenses for clear vision.',
    price: 75,
    imagePlaceholderId: 'product-11',
    category: 'Contact Lenses',
    brand: 'Technoii',
    style: 'N/A',
    material: 'N/A',
    lensType: 'N/A',
  },
  {
    id: '12',
    name: 'Digital Blue Light Blockers',
    description: 'Protect your eyes during screen time with our stylish blue light blocking glasses. Round plastic frames.',
    price: 85,
    imagePlaceholderId: 'product-12',
    category: 'Eyewear',
    brand: 'Technoii',
    style: 'Round',
    material: 'Plastic',
    lensType: 'Blue Light',
  },
];
